### ISSUE TITLE
Download of artifact fails when it contains a space

### ISSUE THREAD

**Issue by sumsum77** [shreyanshp/bitrise-step-getapp#1]
Shen trying to download an artifact having a space in its name the step fails.

Having artifact name "app int.ipa" the final download fails with error 
`/tmp/bitrise424921353/step_src/step.sh: line 25: ${artifact_name}: ambiguous redirect`

Changing the final download from using curl to wget would resolve the issue...
See #2

**Comment by sumsum77** [comment]
simply changing to wget would not completely resolve the issue, as this would include the whole amazon download url in the filename, which is not what is wanted, adding quotes around output filename in curl could help though

**Comment by shreyanshp** [comment]
Sent for release 0.2.0 as a fix - https://github.com/bitrise-io/bitrise-steplib/pull/2529
